# Generated by Django 2.2 on 2020-08-31 20:35

from django.db import migrations, models
from blancas.surnames import surnames


class Migration(migrations.Migration):

    initial = True

    dependencies = [('blancas', '0002_surnames')]

    def insert_surnames(apps, schema_editor):
        provinces = [
            "Almería",
            "Cádiz",
            "Córdoba",
            "Granada",
            "Huelva",
            "Jaén",
            "Málaga",
            "Sevilla",
            "Ceuta",
            "Melilla"
        ]

        Province = apps.get_model("blancas", "Province")
        for item in provinces:
            Province.objects.bulk_create(
                [Province(name=item)]
            )

    def reverse_func(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        Surnames = apps.get_model("blancas", "Surname")
        

    operations = [
        migrations.RunPython(insert_surnames, reverse_func)
    ]
