# Generated by Django 2.2 on 2020-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blancas', '0004_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='client_ip',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
