# Generated by Django 2.2 on 2020-08-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('O', 'Once')], default='O', max_length=1)),
                ('hour', models.TimeField()),
                ('week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'Dicember')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent', models.DateTimeField()),
                ('crontab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_mails.Crontab')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emails', models.ManyToManyField(to='cycle_mails.Recipient')),
            ],
        ),
        migrations.AddField(
            model_name='crontab',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_mails.Reunion'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_mails.Reunion')),
            ],
        ),
    ]
