# Generated by Django 2.2 on 2020-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_mails', '0002_content_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontab',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='week',
            field=models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True),
        ),
    ]
